version: "3"
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=gobarber
        ports:
            - "5432:5432"
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    app:
        depends_on:
            - mongo
            - postgres
            - redis
        build: .
        env_file: .env
        command: bash -c "yarn sequelize db:migrate && yarn dev"
        ports:
            - "3333:3333"

